"""add bid generator knowledge image assets

Revision ID: 0007_bid_generator_knowledge_images
Revises: 0006_bid_generator_tables
Create Date: 2026-05-28
"""

from alembic import op
from sqlalchemy import text


revision = "0007_bid_kb_images"
down_revision = "0006_bid_generator_tables"
branch_labels = None
depends_on = None


CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS bid_generator.knowledge_image_assets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_hash TEXT UNIQUE NOT NULL,
  placeholder TEXT UNIQUE NOT NULL,
  source_doc TEXT NOT NULL DEFAULT '',
  source_page INTEGER NULL,
  nearby_text_sanitized TEXT NULL,
  caption TEXT NOT NULL DEFAULT '',
  image_type TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '',
  tags_json TEXT NOT NULL DEFAULT '[]',
  caption_status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""

CREATE_INDEX_SQLS = (
    "CREATE INDEX IF NOT EXISTS idx_bid_knowledge_image_assets_image_hash ON bid_generator.knowledge_image_assets(image_hash)",
    "CREATE INDEX IF NOT EXISTS idx_bid_knowledge_image_assets_placeholder ON bid_generator.knowledge_image_assets(placeholder)",
    "CREATE INDEX IF NOT EXISTS idx_bid_knowledge_image_assets_source_doc ON bid_generator.knowledge_image_assets(source_doc)",
    "CREATE INDEX IF NOT EXISTS idx_bid_knowledge_image_assets_caption_status ON bid_generator.knowledge_image_assets(caption_status)",
)


def _execute(sql: str) -> None:
    op.get_bind().execute(text(sql))


def upgrade() -> None:
    _execute('CREATE SCHEMA IF NOT EXISTS "bid_generator"')
    _execute(CREATE_TABLE_SQL)
    for statement in CREATE_INDEX_SQLS:
        _execute(statement)


def downgrade() -> None:
    # Intentionally non-destructive: knowledge image assets can be regenerated,
    # but dropping them automatically would discard manual caption edits.
    pass
